apiVersion: v1
kind: Secret
metadata:
  name: ${aio_trust_secret_name}
  namespace: ${aio_cluster_namespace}
type: kubernetes.io/tls
data:
  tls.crt: "${aio_ca_cert_pem}"
  tls.key: "${aio_ca_key_pem}"