apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ${aio_spc_name}
  namespace: ${aio_cluster_namespace}
spec:
  provider: "azure"
  parameters:
    usePodIdentity: "false"
    keyvaultName: "${aio_kv_name}"
    objects: |
      array:
        - |
          objectName: placeholder-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: sp-aio-secret
          objectType: secret
          objectVersion: ""
    tenantId: ${aio_tenant_id}